version: "3.8"
services:
   mysql:
      image: mysql:latest
      hostname: mysql
      container_name: mysql
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 6
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./data/mysql/data:/var/lib/mysql
        - ./data/mysql/log:/var/log/mysql
        - ./data/mysql/conf:/etc/mysql/conf.d
   node01:
      image: hadoop3-jdk8:1.0.2
      hostname: node01
      container_name: node01
      ports:
        - 9870:9870 # hdfs web ui
        - 8020:8020 # namenode rpc
      environment:
        - NODE_TYPE=namenode
      volumes:
        - ./data/namenode:/opt/bigdata/hadoop3/data/namenode
      entrypoint: ["/entrypoint.sh"]
   node02:
      image: hadoop3-jdk8:1.0.2
      hostname: node02
      container_name: node02
      environment:
        - NODE_TYPE=datanode
      volumes:
        - ./data/datanode02:/opt/bigdata/hadoop3/data/datanode
      entrypoint: ["/entrypoint.sh"]
   node03:
      image: hadoop3-jdk8:1.0.2
      hostname: node03
      container_name: node03
      environment:
        - NODE_TYPE=datanode
      volumes:
        - ./data/datanode02:/opt/bigdata/hadoop3/data/datanode
      entrypoint: ["/entrypoint.sh"]
   hive-metastore:
      image: hive-hadoop3:1.0.2
      hostname: hive-metastore
      container_name: hive-metastore
      restart: always
      ports:
        - 9083:9083
      environment:
        - NODE_TYPE=metastore
      depends_on:
        mysql:
         condition: service_healthy
      entrypoint: ["/entrypoint.sh"]

   spark:
      image: spark-hadoop3:1.0.2
      hostname: spark
      container_name: spark
      entrypoint: ['/entrypoint.sh']
