version: "3.8"
services:
   mysql:
      image: mysql:latest
      hostname: mysql
      container_name: mysql
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 6
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
        - TZ=Asia/Shanghai
      volumes:
        - ./data/mysql/data:/var/lib/mysql
        - ./data/mysql/log:/var/log/mysql
        - ./data/mysql/conf:/etc/mysql/conf.d
        - ./data/mysql/my.cnf:/etc/my.cnf
      networks:
          - hadoop
   node01:
      image: hadoop3-jdk8:1.0.10
      hostname: node01
      container_name: node01
      healthcheck:
        test: ["CMD", "zkServer.sh" ,"status"]
        interval: 10s
        timeout: 5s
        retries: 6
      ports:
        - 9870:9870 # hdfs web ui
        - 8020:8020 # namenode rpc
        - 8088:8088 # yarn webui
        - 8032:8032 # resourcemanager rpc
        - 2181:2181 # zookeeper rpc
        - 16010:16010 # hbase webui
      environment:
        - NODE_TYPE=master
        - myid=1
      volumes:
        - ./data/node01/namenode:/opt/bigdata/hadoop3/data/namenode
        - ./data/node01/zookeeper:/opt/bigdata/zookeeper/data/
      entrypoint: ["/entrypoint.sh"]
      networks:
          - hadoop
   node02:
      image: hadoop3-jdk8:1.0.10
      hostname: node02
      container_name: node02
      ports:
        - 2182:2181 # zookeeper rpc
      environment:
        - NODE_TYPE=worker
        - myid=2
      volumes:
        - ./data/node02/datanode:/opt/bigdata/hadoop3/data/datanode
        - ./data/node02/zookeeper:/opt/bigdata/zookeeper/data/
      entrypoint: ["/entrypoint.sh"]
      networks:
          - hadoop
   node03:
      image: hadoop3-jdk8:1.0.10
      hostname: node03
      container_name: node03
      ports:
        - 2183:2181 # zookeeper rpc
      environment:
        - NODE_TYPE=worker
        - myid=3
      volumes:
        - ./data/node03/datanode:/opt/bigdata/hadoop3/data/datanode
        - ./data/node03/zookeeper:/opt/bigdata/zookeeper/data/
      entrypoint: ["/entrypoint.sh"]
      networks:
          - hadoop
   hive:
      image: hive-hadoop3:1.0.10
      hostname: hive
      container_name: hive
      restart: always
      ports:
        - 9083:9083
        - 10000:10000
      environment:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./data/metastore:/opt/bigdata/metastore/data
      depends_on:
        mysql:
         condition: service_healthy
      entrypoint: ["/entrypoint.sh"]
      networks:
          - hadoop
   client:
      image: client-hadoop3:1.0.10
      hostname: client
      container_name: client
      environment:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      entrypoint: ['/entrypoint.sh']
      networks:
          - hadoop
networks:
  hadoop:
    driver: bridge
